## 인공지능 개론 3주차

### 2주차 복습
classification은 정확도와 confusion_matrix를 이용해서 성능을 평가한다.

**정확도**: 전체 test에서 맞춘 갯수를 나타낸다 

**confusion_matrix** : [
    [48, 2],
    [5, 45]
]

48: 정답이 0인데, 0으로 결과가 나온 데이터가 48개란 뜻.
2 : 정답이 0인데, 1로 결과가 나온 데이터가 2개란 뜻.
5 : 정답이 1인데, 0으로 결과가 나온 데이터가 5개란 뜻.
45: 정답이 1인데, 1로 결과가 나온 데이터가 45개란 뜻. 


### GPT 잘 다루는 법

1. pros and cons
2. 구획화하기 (문제 쪼개기)
3. 실제 값을 대입해보기

### IRIS 데이터 실습

In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [14]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

file_path ="/Users/yunseongmun/Documents/Ai_Lecture/data/iris/iris.data"
headers = ['sepal length in cm', 'sepal width in cm', 'petal length in cm','petal width in cm', 'class']

df = pd.read_csv(file_path, header=None, names=headers)
df

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
0                  0.2     Iris-setosa  
1                  0.2     Iris-setosa  
2                  0.2     Iris-setosa  
3                  0.2     Iris-setosa  
4                  0.2     Iris-setosa  
..                 ...             ...  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica  

[150 rows x 5 columns]

In [23]:
x=df.drop('class',axis=1)
x

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm  
0                  0.2  
1                  0.2  
2                  0.2  
3                  0.2  
4                  0.2  
..                 ...  
145                2.3  
146                1.9  
147                2.0  
148                2.3  
149                1.8  

[150 rows x 4 columns]

In [16]:
y=df['class']
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

In [34]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25,random_state=0)

print(y_train)

61     Iris-versicolor
92     Iris-versicolor
112     Iris-virginica
2          Iris-setosa
141     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: class, Length: 112, dtype: object


In [17]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

 ACCURACY OF OTHER ML CLASSIFIERS


In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [26]:
# Build a logistic regression classifier and predict

iris_lr = LogisticRegression(random_state=0)
iris_lr.fit(x_train, y_train)

pred_lr = iris_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
