## 7주차 시험

머신러닝은 act_level로 머신러닝  
딥러닝은 acitivity_id 딥러닝

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

file_path ="/Users/yunseongmun/Documents/Ai_Lecture/data/PAMAP_features.csv"

df = pd.read_csv(file_path,index_col=0)
df

sub_id  activity_id  ... ankle_gyr_yz_cor  ankle_gyr_xz_cor
3006        2           17  ...        -0.003001         -0.638866
3497        2            4  ...        -0.654575          0.391363
14495       7            5  ...        -0.528138          0.402147
13278       7           17  ...         0.237828         -0.729771
14969       8            3  ...         0.066954          0.057685
...       ...          ...  ...              ...               ...
10708       6            2  ...        -0.000800          0.031654
4870        3            2  ...        -0.076216          0.009411
11822       6            4  ...        -0.442849          0.063207
3866        2            7  ...        -0.627185          0.436639
3450        2           13  ...        -0.662742         -0.085954

[11773 rows x 67 columns]

In [17]:
# 레이블 확인
print(df['activity_id'].value_counts())

activity_id
17    1539
4     1525
3     1220
1     1203
7     1196
2     1162
16    1099
6     1035
5      593
12     522
13     428
24     251
Name: count, dtype: int64


In [18]:
#subject 갯수
print(df['sub_id'].value_counts())

sub_id
5    1651
2    1618
8    1576
6    1556
1    1518
7    1430
4    1353
3    1042
9      29
Name: count, dtype: int64


In [19]:
# 'sub_id'와 'act_level' 열을 제거하고 인덱스를 기준으로 데이터프레임 정렬
dl_df = df.drop(columns=['sub_id', 'act_level']).sort_index()
dl_df

activity_id     hr_mean  ...  ankle_gyr_yz_cor  ankle_gyr_xz_cor
1                1  104.509766  ...         -0.368513         -0.292237
3                1  105.839844  ...         -0.438468         -0.192798
4                1  106.339844  ...         -0.389506         -0.293527
5                1  106.644531  ...         -0.042577         -0.305592
6                1  106.705078  ...         -0.017692         -0.214447
...            ...         ...  ...               ...               ...
16811           24  153.171875  ...          0.785436          0.252352
16813           24  153.171875  ...          0.837209          0.155822
16814           24  153.171875  ...          0.826156          0.110417
16815           24  153.091797  ...          0.813039          0.030027
16816           24  153.035156  ...          0.794210         -0.039155

[11773 rows x 65 columns]

In [20]:
# 결측치 확인
dl_df.isnull().sum()

activity_id         0
hr_mean             0
hr_mean_normal      0
hr_std              0
hr_std_normal       0
                   ..
chest_gyr_yz_cor    0
chest_gyr_xz_cor    0
ankle_gyr_xy_cor    0
ankle_gyr_yz_cor    0
ankle_gyr_xz_cor    0
Length: 65, dtype: int64

In [25]:
# 결측치 제거
dl_df = dl_df.dropna()
dl_df.isnull().sum()

activity_id         0
hr_mean             0
hr_mean_normal      0
hr_std              0
hr_std_normal       0
                   ..
chest_gyr_yz_cor    0
chest_gyr_xz_cor    0
ankle_gyr_xy_cor    0
ankle_gyr_yz_cor    0
ankle_gyr_xz_cor    0
Length: 65, dtype: int64

In [27]:
# X,y 분리
X = dl_df.drop('activity_id',axis=1)
y = df['activity_id']

In [29]:
# 원 핫 인코딩
Y = pd.get_dummies(y).values
Y

array([[False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [30]:
# Numpy 변환
X = X.values
X

array([[ 1.04509766e+02,  1.39346354e+00,  9.52667354e-01, ...,
         1.94233980e-01, -3.68513142e-01, -2.92237175e-01],
       [ 1.05839844e+02,  1.41119792e+00,  1.06929139e+00, ...,
         1.87620163e-01, -4.38467566e-01, -1.92798188e-01],
       [ 1.06339844e+02,  1.41786458e+00,  8.53795323e-01, ...,
         8.69030115e-03, -3.89505585e-01, -2.93526888e-01],
       ...,
       [ 1.53171875e+02,  2.83651620e+00,  3.67738646e-01, ...,
         2.39494552e-01,  8.26156340e-01,  1.10416953e-01],
       [ 1.53091797e+02,  2.83503328e+00,  2.82522694e-01, ...,
         1.52745591e-01,  8.13039484e-01,  3.00268186e-02],
       [ 1.53035156e+02,  2.83398437e+00,  1.74267472e-01, ...,
         8.72375717e-02,  7.94209858e-01, -3.91545895e-02]])

In [34]:
# train, test 분리
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

print(X_train.shape[1])
print(y_train.shape[1])

64
12


In [35]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(30,input_shape=(X_train.shape[1],),activation='sigmoid'))
model.add(Dense(20,activation='sigmoid'))
model.add(Dense(15,activation='sigmoid'))
model.add(Dense(y_train.shape[1],activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                1950      
                                                                 
 dense_1 (Dense)             (None, 20)                620       
                                                                 
 dense_2 (Dense)             (None, 15)                315       
                                                                 
 dense_3 (Dense)             (None, 12)                192       
                                                                 
Total params: 3,077
Trainable params: 3,077
Non-trainable params: 0
_________________________________________________________________


/Users/yunseongmun/anaconda3/lib/python3.11/site-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [36]:
model_history=model.fit(x=X_train, y=y_train, epochs=30, batch_size=32,validation_split= 0.1)
Y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(Y_pred,axis=1)

Epoch 1/30


2024-04-15 10:48:14.242788: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


265/265 [==============================] - 1s 1ms/step - loss: 2.3971 - accuracy: 0.1330 - val_loss: 2.4055 - val_accuracy: 0.1444
Epoch 2/30
265/265 [==============================] - 0s 837us/step - loss: 2.3877 - accuracy: 0.1376 - val_loss: 2.3994 - val_accuracy: 0.1157
Epoch 3/30
265/265 [==============================] - 0s 883us/step - loss: 2.3887 - accuracy: 0.1271 - val_loss: 2.3974 - val_accuracy: 0.1157
Epoch 4/30
265/265 [==============================] - 0s 824us/step - loss: 2.3873 - accuracy: 0.1337 - val_loss: 2.4079 - val_accuracy: 0.1444
Epoch 5/30
265/265 [==============================] - 0s 841us/step - loss: 2.3881 - accuracy: 0.1350 - val_loss: 2.4083 - val_accuracy: 0.1157
Epoch 6/30
265/265 [==============================] - 0s 811us/step - loss: 2.3870 - accuracy: 0.1314 - val_loss: 2.4025 - val_accuracy: 0.1444
Epoch 7/30
265/265 [==============================] - 0s 1ms/step - loss: 2.3878 - accuracy: 0.1305 - val_loss: 2.4079 - val_accuracy: 0.1157
Epoch 8

In [37]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       247
           1       0.00      0.00      0.00       236
           2       0.00      0.00      0.00       236
           3       0.12      1.00      0.21       282
           4       0.00      0.00      0.00       122
           5       0.00      0.00      0.00       222
           6       0.00      0.00      0.00       242
           7       0.00      0.00      0.00       115
           8       0.00      0.00      0.00        86
           9       0.00      0.00      0.00       234
          10       0.00      0.00      0.00       284
          11       0.00      0.00      0.00        49

    accuracy                           0.12      2355
   macro avg       0.01      0.08      0.02      2355
weighted avg       0.01      0.12      0.03      2355

[[  0   0   0 247   0   0   0   0   0   0   0   0]
 [  0   0   0 236   0   0   0   0   0   0   0   0]
 [  0   0   0 236   0   0   0  

/Users/yunseongmun/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yunseongmun/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yunseongmun/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
